spring:
  application:
    name: authorization
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: misha
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #spring:
#  application:
#    name: authorization
#  datasource:
#    url: jdbc:h2:mem:security-security
#    driverClassName: org.h2.Driver
#    username: root
#    password: root
#  jpa:
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL81Dialect
#    hibernate:
#      ddl-auto: none
#  liquibase:
#    change-log: db/changelog/db.changelog-master.yaml
#  jpa:
#    hibernate:
#      naming:
#        database-platform: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
