version: '3'

services:
  postgres:
    image: 'postgres:13'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=misha'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=misha'